export const client = {
  name: "Romani Resin and Resurfacing Ltd",
  tagline: "Professional Resin Surfacing in Bradford — Quality You Can Trust",
  description: "Professional resin surfacing services in Bradford and surrounding areas. Trusted local experts with 3 Google reviews.",
  category: "Resin Surfacing",
  yearEstablished: "2015",
  phone: "",
  email: "",
  website: "",
  address: "",
  city: "Bradford",
  county: "",
  postcode: "",
  basedIn: "Bradford",
  founderName: "Michael",
  founderSurname: "",
  founderRole: "Director",
  facebook: "",
  instagram: "",
  linkedin: "",
  twitter: "",
  googleRating: "5",
  reviewCount: "3",
  services: [
    { title: "Garden Design", description: "Bespoke garden designs tailored to your lifestyle and space.", icon: "tree" },
    { title: "Landscaping", description: "Complete hard and soft landscaping to transform your outdoor area.", icon: "shovel" },
    { title: "Paving & Patios", description: "Beautiful paving solutions using premium natural stone and porcelain.", icon: "wall" },
    { title: "Planting Schemes", description: "Year-round colour and interest with expertly curated planting plans.", icon: "flower" },
  ],
  cinematic: {
    frameCount: 181, frameDir: "/frames/", framePrefix: "frame_", frameExtension: ".jpg",
    framePadding: 4, scrollLength: "500vh", mobileFrameCount: 181, mobileFrameDir: "/frames-mobile/",
    scrubSpeed: 0.5, heroStillImage: "/images/hero-still.jpg", heroStillImageMobile: "/images/hero-still-mobile.jpg",
  },
  beforeAfter: { beforeImage: "/images/before.jpg", afterImage: "/images/after.jpg", beforeLabel: "Current Garden", afterLabel: "Our Vision" },
  transformations: [
    { before: "/images/before.jpg", after: "/images/after.jpg", label: "Complete Garden Renovation" },
    { before: "/images/patio-before.jpg", after: "/images/patio-after.jpg", label: "Patio & Fencing" },
    { before: "/images/front-before.jpg", after: "/images/front-after.jpg", label: "Front Garden" },
    { before: "/images/lawn-before.jpg", after: "/images/lawn-after.jpg", label: "Lawn Restoration" },
    { before: "/images/fence-before.jpg", after: "/images/fence-after.jpg", label: "New Fencing" },
    { before: "/images/deck-before.jpg", after: "/images/deck-after.jpg", label: "Decking & Furniture" },
    { before: "/images/path-before.jpg", after: "/images/path-after.jpg", label: "Garden Path" },
    { before: "/images/border-before.jpg", after: "/images/border-after.jpg", label: "Planting Borders" },
    { before: "/images/drive-before.jpg", after: "/images/drive-after.jpg", label: "Driveway" },
  ] as { before: string; after: string; label: string }[],
  reviews: [
    { name: "Laura E", rating: 5, text: "We were really pleased with the excellent work that Romani Resin carried out for us.  Very hardworking team and very tidy in their work.  They did a fantastic job of our fencing, new patio and block paving.  We would not hesitate to recommend them to others and to use them again for future projects.", date: "a year ago" },
    { name: "Grace", rating: 5, text: "Thank you very much it was a pleasure.", date: "a year ago" },
    { name: "Matty Walker", rating: 5, text: "Brilliant set of lads!! Very polite, arrived on time, got the job done in the time they said they would, Garden looks mint.. highly recommended, thanks again chaps see you next time… ill get saving for my front garden doing as i do want that doing as well.", date: "a year ago" },
  ] as { name: string; rating: number; text: string; date: string; badge?: string }[],
  seo: {
    title: "Romani Resin and Resurfacing Ltd | Professional Resin Surfacing in Bradford",
    description: "Professional resin surfacing in Bradford. 5 stars on Google with 3 reviews. Quality workmanship guaranteed.",
  },
};
